baseURL = 'http://example.org/'
languageCode = 'zh-cn'
title = "Arno Wei's blog"
theme = 'hugo-coder'
defaultContentLanguage = 'zh-cn'
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true

[params]
author = "Arno Wei"
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "Arno Wei's personal website"
keywords = "blog,developer,personal"
info = ["Deep learning", "CV"]
# avatarURL = "images/avatar.jpg"
#gravatar = "john.doe@example.com"
dateFormat = "02 Jan 2006"
since = 2018
# Git Commit in Footer, uncomment the line below to enable it
# commit = "https://github.com/luizdepra/hugo-coder/tree/"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
math = true
colorScheme = "auto"

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/buptweixin"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
